import { useMemo, useState } from 'react';
import { useAppData } from '../hooks/useAppData.jsx';
import { Field } from '../components/Forms';
import { calculatePerformance } from '../utils/performance';
import { PageTitle } from './Subjects';

export default function Questions() {
  const data = useAppData();
  const firstSubject = data.subjects[0];
  const [form, setForm] = useState({ subjectId: firstSubject?.id || '', contentId: firstSubject?.contents[0]?.id || '', type: 'múltipla escolha', prompt: '', options: 'A\nB\nC\nD', correctAnswer: '' });
  const [answers, setAnswers] = useState({});
  const contents = useMemo(() => data.subjects.find((s) => s.id === form.subjectId)?.contents || [], [data.subjects, form.subjectId]);
  function submit(event) { event.preventDefault(); data.addQuestion({ ...form, options: form.type === 'cards' ? [] : form.options.split('\n').filter(Boolean), answer: form.type === 'cards' ? form.correctAnswer : undefined }); setForm({ ...form, prompt: '', correctAnswer: '' }); }
  return <div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-10"><PageTitle kicker="Banco de questões" title="Questões e desempenho" text={`Desempenho geral: ${calculatePerformance(data.questions)}%`} /><div className="grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={submit} className="glass-card space-y-3 p-5"><Field label="Matéria"><select className="input-field" value={form.subjectId} onChange={(e) => setForm({ ...form, subjectId: e.target.value })}>{data.subjects.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Conteúdo"><select className="input-field" value={form.contentId} onChange={(e) => setForm({ ...form, contentId: e.target.value })}>{contents.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><Field label="Tipo"><select className="input-field" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option>múltipla escolha</option><option>verdadeiro ou falso</option><option>cards</option></select></Field><Field label="Enunciado / frente do card"><textarea required className="input-field" value={form.prompt} onChange={(e) => setForm({ ...form, prompt: e.target.value })} /></Field>{form.type === 'múltipla escolha' && <Field label="Alternativas (uma por linha)"><textarea className="input-field" value={form.options} onChange={(e) => setForm({ ...form, options: e.target.value })} /></Field>}<Field label="Resposta correta / verso"><input required className="input-field" value={form.correctAnswer} onChange={(e) => setForm({ ...form, correctAnswer: e.target.value })} /></Field><button className="btn-primary w-full">Cadastrar questão</button></form><section className="space-y-4">{data.questions.map((question) => <article key={question.id} className="glass-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="rounded-full bg-white/5 px-3 py-1 text-xs font-bold capitalize text-teal-100">{question.type}</p><p className="text-sm text-slate-400">Tentativas: {question.attempts?.length || 0}</p></div><h2 className="mt-4 text-xl font-black">{question.prompt}</h2><div className="mt-4 flex flex-wrap gap-2">{(question.options?.length ? question.options : ['Verdadeiro', 'Falso', question.answer].filter(Boolean)).map((option) => <button key={option} onClick={() => { setAnswers({ ...answers, [question.id]: option }); data.answerQuestion(question.id, option); }} className="btn-outline py-2">{option}</button>)}</div>{answers[question.id] && <p className={`mt-4 font-bold ${answers[question.id] === (question.correctAnswer || question.answer) ? 'text-teal-200' : 'text-red-200'}`}>{answers[question.id] === (question.correctAnswer || question.answer) ? 'Você acertou!' : 'Você errou. Revise a teoria.'}</p>}</article>)}</section></div></div>;
}
