import { useState } from 'react';
import { useAppData } from '../hooks/useAppData.jsx';
import { Field } from '../components/Forms';
import { PageTitle } from './Subjects';

export default function Tasks() {
  const data = useAppData();
  const [form, setForm] = useState({ title: '', description: '', subjectId: data.subjects[0]?.id || '', dueDate: new Date().toISOString().slice(0, 10), type: 'tarefa', priority: 'média', status: 'pendente' });
  function submit(event) { event.preventDefault(); data.addTask(form); setForm({ ...form, title: '', description: '' }); }
  return <div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-10"><PageTitle kicker="Atividades" title="Tarefas, provas e trabalhos" /><div className="grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={submit} className="glass-card space-y-3 p-5"><Field label="Título"><input className="input-field" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="Descrição"><textarea className="input-field" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><Field label="Matéria"><select className="input-field" value={form.subjectId} onChange={(e) => setForm({ ...form, subjectId: e.target.value })}>{data.subjects.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Entrega"><input className="input-field" type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></Field><Field label="Tipo"><select className="input-field" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{['tarefa', 'prova', 'trabalho', 'revisão', 'apresentação', 'evento'].map((item) => <option key={item}>{item}</option>)}</select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Prioridade"><select className="input-field" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{['baixa', 'média', 'alta'].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Status"><select className="input-field" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{['pendente', 'em andamento', 'concluído'].map((item) => <option key={item}>{item}</option>)}</select></Field></div><button className="btn-primary w-full">Adicionar atividade</button></form><section className="space-y-3">{data.tasks.map((task) => <article key={task.id} className="glass-card flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-teal-200">{task.type} · {task.priority}</p><h2 className="text-xl font-black">{task.title}</h2><p className="text-sm text-slate-400">{task.description}</p></div><div className="flex items-center gap-2"><input className="input-field" type="date" value={task.dueDate} onChange={(e) => data.updateTask(task.id, { dueDate: e.target.value })} /><select className="input-field" value={task.status} onChange={(e) => data.updateTask(task.id, { status: e.target.value })}><option>pendente</option><option>em andamento</option><option>concluído</option></select></div></article>)}</section></div></div>;
}
